-- Schema + seed para Shopify Dev Docs
-- Ejecuta este archivo en MySQL 8+

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS pages;
DROP TABLE IF EXISTS site_settings;

CREATE TABLE site_settings (
  setting_key VARCHAR(100) NOT NULL PRIMARY KEY,
  setting_value TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE pages (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(120) NOT NULL UNIQUE,
  label VARCHAR(180) NOT NULL,
  file_name VARCHAR(180) NOT NULL UNIQUE,
  nav_order INT NOT NULL,
  hero_title TEXT NOT NULL,
  hero_subtitle TEXT NOT NULL,
  card1_title TEXT NOT NULL,
  card1_body TEXT NOT NULL,
  card2_title TEXT NOT NULL,
  card2_body TEXT NOT NULL,
  card3_title TEXT NOT NULL,
  card3_body TEXT NOT NULL,
  code_snippet MEDIUMTEXT NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO site_settings (setting_key, setting_value) VALUES
  ('site_title', 'Shopify Dev Docs'),
  ('brand_title', 'Shopify Dev Docs'),
  ('brand_subtitle', 'Shopify + Liquid en castellano'),
  ('hero_badge_text', 'Shopify Dev Docs'),
  ('search_placeholder', 'Buscar seccion...'),
  ('search_button_label', 'Buscar'),
  ('no_results_label', 'Sin resultados'),
  ('sidebar_foot', 'Documentacion visual y profesional del ecosistema Shopify: themes, Liquid, arquitectura y rendimiento.'),
  ('footer_left', 'Shopify Dev Docs'),
  ('footer_right_prefix', 'Contenido en MySQL'),
  ('playground_title', 'Simulador server-side'),
  ('playground_description', 'Procesa template y JSON en PHP, sin JavaScript.'),
  ('playground_template_label', 'Template'),
  ('playground_data_label', 'Datos JSON'),
  ('playground_button_label', 'Ejecutar simulacion'),
  ('playground_output_label', 'Salida'),
  ('playground_default_template', '<h2>{{ product.title | upcase }}</h2>
<p>Precio: {{ product.price | money }}</p>
{% if product.in_stock %}
<button>Añadir al carrito</button>
{% endif %}'),
  ('playground_default_data', '{
  "product": {
    "title": "Wave Runner",
    "price": 12900,
    "in_stock": true
  }
}');

INSERT INTO pages (
  slug, label, file_name, nav_order,
  hero_title, hero_subtitle,
  card1_title, card1_body,
  card2_title, card2_body,
  card3_title, card3_body,
  code_snippet
) VALUES
  ('inicio', 'Inicio', 'index.php', 1, 'Shopify Dev Docs: Guia profesional completa de Shopify, Liquid y Temas modernos', 'Documentacion visual, practica y en profundidad en castellano. Aprende a construir, optimizar y mantener temas Shopify de nivel profesional con arquitectura escalable.', '📚 Ruta de aprendizaje estructurada', 'Comienza con Introduccion a Shopify para entender la plataforma. Continua con Liquid fundamentals, luego Sections y Templates. Consolida con Theme Architecture, Performance y Best Practices. Esta secuencia garantiza comprension profunda y aplicacion practica.', '🎯 Cobertura completa del ecosistema', 'Todo lo que necesitas: Shopify plataforma, Liquid lenguaje, Sections modulares, Snippets reutilizables, Templates, Products, Collections, Metafields estructurados, APIs (Ajax, Storefront, Admin), CLI, Cart, Checkout, Performance y Best Practices profesionales.', '🚀 Empieza ahora', 'Navega con el menu lateral, utiliza la busqueda para encontrar temas especificos rapidamente. Cada pagina incluye explicaciones detalladas, patrones recomendados y errores comunes a evitar.', ''),
  ('introduccion-shopify', 'Introduccion a Shopify', 'introduccion-shopify.php', 2, 'Introduccion profunda a Shopify y su arquitectura de plataforma', 'Domina los conceptos fundacionales: admin, storefront, temas, apps, APIs, scopes y modelos de datos. Comprende como Shopify integra comercio, checkout y personalizacion.', '🏗️ Arquitectura de capas en Shopify', 'Shopify es una plataforma multicapa: (1) Admin & Datos: gestion de productos, ordenes, clientes; (2) Checkout: infraestructura asegurada y confiable; (3) Storefront: capa personalizable con Liquid y temas. Cada capa tiene APIs y limites claros. Entender estas separaciones permite tomar decisiones arquitectonicas correctas.', '🎨 Online Store 2.0 y arquitectura moderna', 'OS 2.0 revoluciono themes con: JSON templates (vs settings.json antiguo), Sections dinamicas editables, App Blocks para extensibilidad sin acoplo, Theme Store mejorado. Permite merchants editar sin codigo. Usa esta flexibilidad responsablemente: expone opciones claras, da defaults utiles, limita opciones a lo necesario.', '⚠️ Error critico a evitar', 'No mezcles reglas de negocio con presentacion. El tema NO debe validar inventario, calcular impuestos ni verificar permisos. Usa Liquid solo para renderizar, delega logica al Admin o APIs. Esto mantiene el codigo mantenible, testeable y escalable.', ''),
  ('liquid', 'Liquid', 'liquid.php', 3, 'Liquid: lenguaje templating de Shopify en profundidad', 'Variables, objetos, filtros, loops, condiciones, schema JSON, render, assign, capture y paginacion. Domina Liquid para plantillas mantenibles y seguras.', '🧠 Modelo mental de Liquid', 'Liquid es un lenguaje de templating logico-seguro: (1) Entrada: objetos disponibles del contexto; (2) Transformacion: filtros y operadores; (3) Control: if/unless, for, case; (4) Composicion: render y include. No es Turing-completo intencionalmente. Piensa en Liquid como descripciones declarativas de cómo renderizar HTML, no como programacion imperativa.', '✍️ Sintaxis y patrones esenciales', 'Domina: Variables ({{ variable }}), Objetos (product.title), Filtros ({{ price | money }}), Assign ({% assign x = value %}), Capture ({% capture %}), Render ({% render ''snippet'' %}), If/Unless, For loops, Paginate. Cada uno resuelve un problema especifico. Usa render para compartir snippets, assign para variables temporales, capture para bloques complejos.', '🚫 Errores y anti-patrones comunes', 'Evita: (1) Condicionales densas sin claridad; (2) Variables globales implicitas sin documentacion; (3) Logica de negocio en templates; (4) Renders excesivos sin limite. En su lugar: usa funciones claras, documenta contratos, mantén Liquid para presentacion, y audita performance de renders.', ''),
  ('sections', 'Sections', 'sections.php', 4, 'Sections: componentes modulares y editables en Shopify', 'Construye components reutilizables con schema editable, bloques dinamicos y configuracion clara para merchants. Arquitectura base de OS 2.0.', '🔧 Anatomia completa de una Section', 'Una section es un componente con 3 partes: (1) Schema JSON: define opciones editables (text, color, image, etc), bloques anidados, presets; (2) Liquid: renderiza HTML usando valores del schema; (3) CSS/JS: estilos y comportamiento aislado. La section es la unidad modular fundamental. Diseña pensando en reutilizacion: busca patrones, extrae a sections, expone bien el schema.', '✅ Buenas practicas de design', '(1) Namespacing: usa IDs/clases prefijadas para evitar conflictos; (2) Schema: labels claros, defaults sensatos, validaciones (minmax, opciones limitadas); (3) Bloques: limita cantidad y tipos; (4) Performance: no renders innecesarios, lazy-load imagenes; (5) Accesibilidad: alt en imagenes, ARIA labels, contraste valido.', '🔌 App Blocks y extensibilidad', 'Reserva zonas de templates (hero, product-info, footer) para app blocks. Usa @app directive en schema. No asuelas la app en código - deja que se inyecte. Esto permite merchants integrar apps sin acoplar el tema a cada una. Documenta bien los blocktypes que aceptas.', ''),
  ('snippets', 'Snippets', 'snippets.php', 5, 'Snippets: componentes Liquid reutilizables sin schema editable', 'Fragmentos de código para reutilizacion en templates. Ideal para componentes sin opciones editables por merchant. Complemento ligero de sections.', '🎯 Cuando extraer a snippet', 'Extrae patrones repetidos como product-card, price-display, icon-row, empty-state, mini-cart. Cada snippet debe tener responsabilidad clara. Si los params son muchos, tal vez sea section. Un snippet bien hecho es una abstraccion limpia reutilizable en multiples templates.', '📤 Render con parametros explícitos', 'Usa {% render ''card'' with product: product, show_rating: true %}. Parametros explicitos reducen acoplamiento, facilitan testing y evolucion. El snippet no tiene acceso al scope global a menos que lo pases. Esto hace codigo mas predecible y mantenible en equipo.', '🚫 Errores y anti-patrones', 'Evita: (1) Snippets gigantes con 15+ condicionales; (2) Acceso implicito a variables globales; (3) Duplicar logic; (4) Renders dentro de loops sin optimizacion. En su lugar: divide en snippets pequenos, pasa params, reutiliza, y considera liquid caching si renders son pesados.', ''),
  ('templates', 'Templates', 'templates.php', 6, 'Templates: raices JSON que orquestan cada tipo de página', 'Desde product.json hasta collection.json. Templates integran sections, controlan flujo y definen estructura HTML base de cada tipo de página.', '🏗️ Anatomia de template vs section', 'Template es capa delgada que: (1) Define estructura general; (2) Itera sections; (3) Incluye nav/footer globales. Section es capa rica que: (1) Define schema editable; (2) Contiene logica; (3) Es reutilizable. Principio: templates ligeros, sections robustas. No hagas templates por cada texto unico.', '📋 JSON templates y composition', 'En OS 2.0, usa JSON format: lista de sections con IDs unicas, settings por section, orden personalizable. Merchants pueden reordenar sin tocar codigo. Eso es poder. Documenta bien el modelo de datos esperado en cada section.', '🚫 Anti-patrón comun', 'Crear templates nuevos por cada variacion textual: product-de-verano.json, product-especial.json. Eso es sprawl. En cambio: usa una section hero adaptable con settings de text, color, image. Una template product.json con sections flexibles. Reduce archivos, amplifica poder de merchants.', ''),
  ('products', 'Products', 'products.php', 7, 'Product Detail Pages (PDP): optimizacion integral para conversion', 'Disen~a PDPs que conviertan: variantes claras, galeria responsive, informacion estructurada, recomendaciones y checkout directo.', '🛍️ Objeto product y sus capas', 'Product contiene: (1) Informacion basica: title, description, vendor; (2) Variantes: tipos de producto, precios, SKU, weight; (3) Media: imagenes, videos, 3D models; (4) Datos dinamicos: stock, rating, reviews. Usa selected_or_first_available_variant para default inteligente. Render robusto maneja fallbacks: sin imagen -> placeholder, sin variante -> mensaje.', '🎨 UX de variantes y gallery', 'Flujo: (1) Merchant elige opcion (color, size) -> (2) Actualiza price, stock, media en tiempo real; (3) CTA (Add to Cart) activa/desactiva segun stock. Gallery responde a opcion: muestra imagenes de esa variante. Este flujo mantiene confianza. Usa fetch API para sincronizar sin page reload. ARIA labels en selectores para accesibilidad.', '⚠️ Robustez en edge cases', 'Realidad: (1) Producto sin variantes; (2) Stock en 0; (3) Sin imagenes; (4) Descripcion vacia; (5) Precios con descuento. Maneja cada caso: fallbacks, iconos de estado, mensajes claros. Testing es critico. Audita PDPs contra datos rotos del admin.', ''),
  ('collections', 'Collections', 'collections.php', 8, 'Collections: discovery, filtros y conversion', 'Crea paginas de coleccion rapidas, filtrables, accesibles y orientadas a conversion con paginacion eficiente.', 'Paginacion y performance', 'La paginacion es critica: (1) Evita respuestas de 100+ items; (2) Mejora tiempo de carga; (3) Reduce uso de memoria client; (4) Usa {% paginate %} tag. Default 12-24 items por pagina. Ofrece opcion de cambiar con limites.', 'Filtros y taxonomia', 'Filtra por disponibilidad, precio, atributos, tipo. UI clara: muestra resultados, indica filtros activos, permitir reset, muestra opciones con 0 resultados. Ordena por popularidad, precio, nuevo, resenias.', 'Performance en listados', 'Errores comunes: imagenes sobredimensionadas rompen LCP, cards densas con HTML pesado, renders dentro del loop. Soluciones: srcset en imagenes, CSS minimal, extrae card a snippet, lazy-load.', ''),
  ('metafields', 'Metafields', 'metafields.php', 9, 'Metafields: contenido estructurado y extensible', 'Escala contenido dinamico con definiciones fuertes, contratos de datos estables y migraciones controladas.', 'Modelo de datos y namespace', 'Metafield = namespace.key con tipo especifico (string, integer, json, rich_text). Ejemplo: ''custom.sku_alterno''. Namespacing evita colisiones, tipos garantizan validacion. Disena con disciplina: cada metafield es un contrato de datos.', 'Consumir en Liquid', 'Accede via {{ product.metafields.custom.atributo }}. Valida siempre: {% if product.metafields.custom.atributo %} antes de renderizar. Los metafields son fuente de contenido dinamico. Define bien tipos en admin. Rich text y json requieren parsing especial.', 'Migraciones y breaking changes', 'Cambiar tipo rompe vistas sin migracion. Estrategia: (1) Crear metafield nuevo con tipo correcto; (2) Script para copiar datos; (3) Actualizar templates; (4) Deprecate viejo. Nunca cambies tipo en vivo. Audita en staging antes de produccion.', ''),
  ('theme-architecture', 'Theme Architecture', 'theme-architecture.php', 10, 'Theme Architecture: estructura para mantener velocidad y calidad', 'Organiza carpetas, settings, assets y localizacion de forma escalable. Base para temas profesionales mantenibles.', 'Estructura de directorios', '/layout (layout.liquid con nav/footer), /templates (product.json, collection.json), /sections (componentes reutilizables), /snippets (fragmentos), /assets (CSS, JS, imagenes), /config (settings_schema.json, locales). Cada carpeta tiene responsabilidad clara. Linea de 200+ archivos raiz es red flag.', 'Theme settings y configuracion', 'settings_schema.json centraliza opciones editables: colores, tipografia, max-width. Agrupa por dominio: branding, header, footer. Evita exceso de toggles. Settings se inyectan en Liquid como {{ settings.color_primary }}. Documenta cada uno con label y descripcion. Settings mal diseñados son inmanejables.', 'Localizacion y multi-mercado', 'locale/es.json, locale/en.json con textos. En Liquid accede con {{ ''general.button_add_to_cart'' | t }}. Permite soportar tiendas en multiples idiomas y monedas sin duplicar codigo. Sistema de traduccion es fundamental para temas profesionales.', ''),
  ('shopify-cli', 'Shopify CLI', 'shopify-cli.php', 11, 'Shopify CLI: desarrollo, preview y despliegue para equipos', 'Herramienta profesional para flujos reproducibles, previews por rama y despliegues seguros sin perder configuracion de merchant.', 'Comandos base y flujo diario', 'shopify theme dev: sincroniza cambios locales en vivo a store. shopify theme pull: descarga tema de produccion. shopify theme push: sube a rama nueva. Flujo recomendado: crea rama, dev local, push a preview, QA en vivo, merge y deploy. Define un script reproducible para onboarding rapido.', 'Flujo por ramas y QA', 'Cada rama Git tiene asociada una preview URL. Merchants y QA validan sin tocar produccion. Sistema sensato: nombra ramas (feature/*, bugfix/*), auto-sync con CLI, genera URL preview. Revisa cambios en staging antes de merge a main. Colaboracion clara.', 'Despliegue seguro y reversible', 'Cuidado: shopify theme push --live sobrescribe tema activo. Estrategia: backup antes (shopify theme pull), deploy a horario bajo, tener rollback plan (git revert + push). Los temas son codigo pero merchants agregan contenido: secciones, imagenes, settings. Nunca borres eso accidentalmente.', ''),
  ('apis', 'APIs', 'apis.php', 12, 'APIs en Shopify', 'Elige entre Ajax, Storefront y Admin API segun contexto tecnico y de seguridad.', 'Matriz de eleccion', 'Ajax API para tema, Storefront para headless y Admin para operaciones internas.', 'Seguridad', 'Nunca expongas credenciales privadas en storefront; usa scopes minimos.', 'Versionado', 'Fija version API y revisa changelog de forma periodica.', ''),
  ('cart', 'Cart', 'cart.php', 13, 'Cart architecture', 'Implementa carrito fiable con feedback inmediato y reconciliacion server-side.', 'Flujos base', 'Agregar, actualizar y eliminar lineas con feedback claro y estados de carga accesibles.', 'Estado sincronizado', 'Evita desincronizacion con reconciliacion por respuesta final de servidor.', 'Error comun', 'UI local distinta del carrito real despues de multiples updates rapidos.', ''),
  ('checkout', 'Checkout', 'checkout.php', 14, 'Checkout y limites de personalizacion', 'Optimiza conversion antes de checkout y usa solo extensiones soportadas.', 'Lo que si puedes tocar', 'Usa branding, extensiones permitidas y validaciones previas al checkout.', 'Palancas de conversion', 'La mayor mejora de conversion ocurre en PDP y carrito, no solo en checkout.', 'Error comun', 'Intentar resolver todo en checkout sin optimizar el embudo previo.', ''),
  ('performance', 'Performance', 'performance.php', 15, 'Performance y Core Web Vitals', 'Disena con presupuestos tecnicos y controla regresiones por plantilla.', 'Presupuesto tecnico', 'Fija limites de JS, CSS, imagenes y terceros por tipo de pagina.', 'Imagenes responsivas', 'Genera tamanos segun breakpoint para proteger LCP e INP.', 'Regresiones', 'Audita por template en cada release para detectar impactos silenciosos.', ''),
  ('best-practices', 'Best Practices', 'best-practices.php', 16, 'Best Practices para themes', 'Convenciones, QA y despliegues seguros para equipos de alto rendimiento.', 'Legibilidad', 'Prioriza claridad sobre ingenio para facilitar mantenimiento y onboarding.', 'Release seguro', 'Usa previews, checklist y rollback para publicar sin riesgos innecesarios.', 'Error comun', 'Depender de JS para tareas que Liquid o HTML pueden resolver de forma nativa.', ''),
  ('recursos', 'Recursos', 'recursos.php', 17, 'Recursos recomendados', 'Fuentes clave para seguir aprendiendo y mantenerte actualizado.', 'Documentacion oficial', 'La referencia principal siempre debe ser la documentacion oficial de Shopify.', 'Stack diario', 'CLI, Theme Check, Lighthouse y profiler como base de productividad.', 'Comunidad', 'Sigue changelog y discusiones tecnicas para mantener criterio actualizado.', ''),
  ('playground', 'Playground', 'playground.php', 18, 'Playground de Liquid', 'Sandbox server-side sin JavaScript para practicar sintaxis base de Liquid.', 'Editor y simulador', 'Este playground implementa if/endif, variables y filtros basicos en servidor.', 'Entrada JSON', 'Valida JSON en backend y muestra resultado renderizado con escape seguro.', 'Advertencia', 'Simulador didactico: no reemplaza el parser oficial de Liquid.', '');

SET FOREIGN_KEY_CHECKS = 1;
